service: pbs-schedule

frameworkVersion: '2 || 3'

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: http/schedule.hello
  join:
    handler: http/schedule.join
  proxy:
    handler: http/schedule.proxy
    events:
      - http:
          path: /
          method: any
    environment:
      URL: https://airnet.org.au
